In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
df = pd.read_csv("../data/cleaned/nassau_featured.csv")

In [5]:
product_summary = df.groupby(
    'Product Name'
).agg({
    'Sales':'sum',
    'Gross Profit': 'sum',
    'Units': 'sum',
    'Gross Margin %': 'mean'
}).reset_index()

In [ ]:
#Top 10 Products by Margin
product_summary.sort_values(
    'Gross Profit',
    ascending=False
).head(10)

,Product Name,Sales,Gross Profit,Units,Gross Margin %
13,Wonka Bar -Scrumdiddlyumptious,27874.80,19357.50,7743,69.444444
12,Wonka Bar - Triple Dazzle Caramel,28485.00,18610.20,7596,65.333333
10,Wonka Bar - Milk Chocolate,26867.75,17443.37,8267,64.923077
11,Wonka Bar - Nutty Crunch Surprise,23574.95,16819.95,6755,71.346705
9,Wonka Bar - Fudge Mallows,24890.40,16593.60,6914,66.666667
6,Lickable Wallpaper,7860.00,3930.00,393,50.000000
14,Wonka Gum,597.50,310.70,478,52.000000
0,Everlasting Gobstopper,130.00,104.00,13,80.000000
4,Kazookles,1205.75,92.75,371,7.692308
3,Hair Toffee,76.50,59.50,17,77.777778

In [8]:
#High Sales + Low Margin

product_summary[
    (product_summary['Sales'] >
     product_summary['Sales'].median())
    &
    (product_summary['Gross Margin %'] < 20)
]

  Product Name    Sales  Gross Profit  Units  Gross Margin %
4    Kazookles  1205.75         92.75    371        7.692308